services:
  web:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-https://api.caxiaslixozero.com.br}
    image: lixo-zero-web
    ports:
      - '8080:80'
    restart: unless-stopped
